from backend.extensions import db

class Character(db.Model):
    __tablename__ = 'characters'
    id = db.Column(db.String(255), primary_key=True)
    name = db.Column(db.String(255))
    house = db.Column(db.String(255))
    image = db.Column(db.Text)
    died = db.Column(db.String(255))
    born = db.Column(db.String(255))
    patronus = db.Column(db.String(255))
    gender = db.Column(db.String(50))
    species = db.Column(db.String(100))
    blood_status = db.Column(db.String(100))
    role = db.Column(db.Text)
    wiki = db.Column(db.Text)
    slug = db.Column(db.String(255))
    image_blob = db.Column(db.LargeBinary)
    alias_names = db.Column(db.Text)
    animagus = db.Column(db.Text)
    boggart = db.Column(db.Text)
    eye_color = db.Column(db.String(100))
    family_member = db.Column(db.Text)
    hair_color = db.Column(db.String(100))
    height = db.Column(db.String(50))
    jobs = db.Column(db.Text)
    nationality = db.Column(db.String(100))
    romances = db.Column(db.Text)
    skin_color = db.Column(db.String(100))
    titles = db.Column(db.Text)
    wand = db.Column(db.Text)
    weight = db.Column(db.String(50))
